name: CI

on:
  pull_request:
  push:
    branches: [main, dev, stable]
  workflow_dispatch:

jobs:
  jest-test:
    uses: ./.github/workflows/jest-test.yaml
    runs-on: self-hosted

  create-timestamp:
    uses: ./.github/workflows/create-timestamp.yaml
    runs-on: ubuntu-latest

  create-cache-key:
    uses: ./.github/workflows/create-cache-key.yaml

  android-build:
    strategy:
      matrix:
        arch: [ x86_64, x86, arm64-v8a, armeabi-v7a ]
    uses: ./.github/workflows/android-build.yaml
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}

  android-macos-integration-test:
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a]
    uses: ./.github/workflows/android-macos-integration-test.yaml
    needs: [ create-timestamp, create-cache-key, android-build ]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.arch }}

  android-ubuntu-integration-test-ci:
    strategy:
      matrix:
        config:
          - { abi: x86_64, api-level: 34, target: default }
          - { abi: x86, api-level: 29, target: default }
    uses: ./.github/workflows/android-ubuntu-integration-test-ci.yaml
    needs: [create-timestamp, android-build]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.config.abi }}
      api-level: ${{ matrix.config['api-level'] }}
      target: ${{ matrix.config.target }}

  android-ubuntu-e2e-test-ci:
    strategy:
      matrix:
        config:
          - { abi: x86_64, api-level: 30, target: default }
          - { abi: x86, api-level: 28, target: default }
    uses: ./.github/workflows/android-ubuntu-e2e-test-ci.yaml
    needs: [create-timestamp, android-build]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.config.abi }}
      api-level: ${{ matrix.config['api-level'] }}
      target: ${{ matrix.config.target }}

  ios-build:
    uses: ./.github/workflows/ios-build.yaml
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}

  ios-integration-test:
    uses: ./.github/workflows/ios-integration-test.yaml
    needs: [create-timestamp, ios-build]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}

  # deactivating these for now, until we know how to fix
  # detox run in MACOS.
  #ios-e2e-test:
  #  uses: ./.github/workflows/ios-e2e-test.yaml
  #  needs: [create-timestamp, ios-build]
  #  with:
  #    timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
  #    cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
